# Artificial Neural network

In [1]:
# Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

## # Part 1 - Data Preprocessing

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


## # Encoding categorical data

In [5]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2]) # 2 is the index of the column to be encoded 
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [6]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer # to encode the column
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') 
# 1 is the index of the column to be encoded 
# remainder='passthrough' is used to keep the other columns as it is
# transformers=[('encoder', OneHotEncoder(), [0])] is used to encode the column
print(ct) # to see the object
print("--------------------------------------------------")
X = np.array(ct.fit_transform(X))
print(X[0])

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [1])])
--------------------------------------------------
[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


In [7]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [8]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
print(X_train[0])

[-1.01460667 -0.5698444   1.74309049  0.16958176 -1.09168714 -0.46460796
  0.00666099 -1.21571749  0.8095029   0.64259497 -1.03227043  1.10643166]


## # Part 2 - Building the ANN

In [10]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

In [11]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [12]:
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


In [13]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## # Part 3 - Training the ANN

In [14]:
# Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) 

# adam optimizer is used for stochastic gradient descent
# optimizer = 'adam' is used to update the weights
# loss = 'binary_crossentropy' is used for binary classification
# metrics = ['accuracy'] is used to evaluate the model

# For multiclass classification, loss = 'categorical_crossentropy' is used



In [15]:
# Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


250/250 [==============================] - 3s 3ms/step - loss: 0.4914 - accuracy: 0.7872
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4561 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4428 - accuracy: 0.7962
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4344 - accuracy: 0.7997
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4271 - accuracy: 0.8095
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4199 - accuracy: 0.8160
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4134 - accuracy: 0.8184
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4072 - accuracy: 0.8171
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4007 - accuracy: 0.8204
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3945 - accu

## # Part 4 - Making the predictions and evaluating the model

In [16]:
"""
Homework:
Use our ANN model to predict if the customer with the following informations will leave the bank: 
Geography: France
Credit Score: 600
Gender: Male
Age: 40 years old
Tenure: 3 years
Balance: $ 60000
Number of Products: 2
Does this customer have a credit card? Yes
Is this customer an Active Member: Yes
Estimated Salary: $ 50000
So, should we say goodbye to that customer?

Solution:
"""

'\nHomework:\nUse our ANN model to predict if the customer with the following informations will leave the bank: \nGeography: France\nCredit Score: 600\nGender: Male\nAge: 40 years old\nTenure: 3 years\nBalance: $ 60000\nNumber of Products: 2\nDoes this customer have a credit card? Yes\nIs this customer an Active Member: Yes\nEstimated Salary: $ 50000\nSo, should we say goodbye to that customer?\n\nSolution:\n'

In [17]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

# 1 is used to encode France
# 0 is used to encode Germany
# 0 is used to encode Spain
# 5th value is for Gender: Male => 1 


1/1 [==============================] - 0s 267ms/step
[[False]]


In [18]:
"""
Therefore, our ANN model predicts that this customer stays in the bank!
Important note 1: Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.
Important note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.
"""


'\nTherefore, our ANN model predicts that this customer stays in the bank!\nImportant note 1: Notice that the values of the features were all input in a double pair of square brackets. That\'s because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.\nImportant note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That\'s because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.\n'

In [19]:
# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [20]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1497   98]
 [ 185  220]]


0.8585