### OneHot Encode in a simple numpy array where data is label enocoded.

In [2]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# Given matrix
matrix = np.array([
    [16.2, 13.8, 47.1, 2],
    [16.7, 15.59, 44.53, 0],
    [15.51, 10.55, 40.54, 1],
    [14.41, 11.85, 38.62, 2]
])



In [12]:
# Extract the last column for encoding
# need to reshape because sklearn.onehotencode expects a 2D array

last_column = matrix[:, -1].reshape(-1, 1) # -1 means as many rows as needed, 1 means 1 column
last_column

array([[2.],
       [0.],
       [1.],
       [2.]])

In [10]:
# Initialize OneHotEncoder
onehot_encoder = OneHotEncoder(sparse_output=False)

In [14]:
# Encode the last column
encoded_column = onehot_encoder.fit_transform(last_column)
encoded_column

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Insert the encoded columns back into the original matrix

encoded_matrix = np.hstack((matrix[:, :-1], encoded_column))  # hstack means horizontal stack (add columns)
encoded_matrix

array([[16.2 , 13.8 , 47.1 ,  0.  ,  0.  ,  1.  ],
       [16.7 , 15.59, 44.53,  1.  ,  0.  ,  0.  ],
       [15.51, 10.55, 40.54,  0.  ,  1.  ,  0.  ],
       [14.41, 11.85, 38.62,  0.  ,  0.  ,  1.  ]])